2021-04-23 15:13:25,792 INFO    MainThread:776837 [wandb_setup.py:_flush():69] setting env: {}
2021-04-23 15:13:25,792 INFO    MainThread:776837 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-23 15:13:25,792 INFO    MainThread:776837 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-23 15:13:25,792 INFO    MainThread:776837 [wandb_init.py:_log_setup():336] Logging user logs to ../logs/p1/wandb/run-20210423_151325-baseline_0_0/logs/debug.log
2021-04-23 15:13:25,792 INFO    MainThread:776837 [wandb_init.py:_log_setup():337] Logging internal logs to ../logs/p1/wandb/run-20210423_151325-baseline_0_0/logs/debug-internal.log
2021-04-23 15:13:25,793 INFO    MainThread:776837 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f16a5a55d00>
2021-04-23 15:13:25,793 INFO    MainThread:776837 [wandb_init.py:init():369] calling init triggers
2021-04-23 15:13:25,793 INFO    MainThread:776837 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-04-23 15:13:25,793 INFO    MainThread:776837 [wandb_init.py:init():418] starting backend
2021-04-23 15:13:25,793 INFO    MainThread:776837 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-23 15:13:25,821 INFO    MainThread:776837 [backend.py:ensure_launched():123] starting backend process...
2021-04-23 15:13:25,848 INFO    MainThread:776837 [backend.py:ensure_launched():127] started backend process with pid: 776945
2021-04-23 15:13:25,849 INFO    MainThread:776837 [wandb_init.py:init():423] backend started and connected
2021-04-23 15:13:25,867 INFO    MainThread:776837 [wandb_init.py:init():465] updated telemetry
2021-04-23 15:13:25,880 INFO    MainThread:776837 [wandb_init.py:init():484] communicating current version
2021-04-23 15:13:26,489 INFO    MainThread:776837 [wandb_init.py:init():489] got version response 
2021-04-23 15:13:26,490 INFO    MainThread:776837 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-23 15:13:56,491 INFO    MainThread:776837 [interface.py:_communicate_run():642] couldn't get run from backend
2021-04-23 15:13:56,491 ERROR   MainThread:776837 [wandb_init.py:init():501] backend process timed out
2021-04-23 15:13:56,491 ERROR   MainThread:776837 [wandb_init.py:init():510] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2021-04-23 15:14:05,416 WARNING MainThread:776837 [wandb_init.py:init():764] interrupted
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 744, in init
    run = wi.init()
  File "/home/user/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 513, in init
    backend.cleanup()
  File "/home/user/.local/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 155, in cleanup
    self.wandb_process.join()
  File "/python/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/python/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/python/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
